# Generated by Django 5.1.4 on 2025-01-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='dayUkr',
            field=models.CharField(choices=[('пн', 'Понеділок'), ('вт', 'Вівторок'), ('ср', 'Середа'), ('чт', 'Четвер'), ('пт', "П'ятниця"), ('сб', 'Субота')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timeStart',
            field=models.CharField(choices=[('8-30', '8-30'), ('10-25', '10-25'), ('12-20', '12-20'), ('14-15', '14-15'), ('16-10', '16-10'), ('18-30', '18-30')], max_length=10),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lesson.semester')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.week'),
            preserve_default=False,
        ),
    ]
