# Generated by Django 5.1.4 on 2025-01-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lesson_count_lesson_day_lesson_dayukr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
