# Generated by Django 5.1.4 on 2025-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_remove_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='dayUkr',
            field=models.CharField(choices=[('пн', 'Понеділок'), ('вт', 'Вівторок'), ('ср', 'Середа'), ('чт', 'Четвер'), ('пт', "П'ятниця"), ('сб', 'Субота')], default='пн', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timeStart',
            field=models.CharField(choices=[('8-30', '8-30'), ('10-25', '10-25'), ('12-20', '12-20'), ('14-15', '14-15'), ('16-10', '16-10'), ('18-30', '18-30')], default='8-30', max_length=1000),
        ),
    ]
