# Generated by Django 5.1.4 on 2025-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_lesson_day_alter_lesson_dayukr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='usersId',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
